#!/usr/bin/env python3
"""
setup_test_db.py - FXTS test data setup

Creates (or resets) the CSV files in the data/ directory that act as the
database for development and testing.

Usage:
  python3 setup_test_db.py            # create/reset all CSV files
  python3 setup_test_db.py --verify   # show row counts only
  python3 setup_test_db.py --data-dir /path/to/data
"""

import argparse
import csv
import datetime
import os

# ---------------------------------------------------------------------------
# HourlyData generator (200 bars per cross for SMA-200 support)
# ---------------------------------------------------------------------------

# 200 bars ending at 2026-03-04 15:00 UTC  (starts 2026-02-24 08:00)
_HOURLY_END   = datetime.datetime(2026, 3, 4, 15, 0, 0)
_HOURLY_START = _HOURLY_END - datetime.timedelta(hours=199)


def _gen_bars(ticker, base_open, step, hl_frac, start_id, n=200):
    """Return n consecutive hourly OHLC rows as lists."""
    rows = []
    o = base_open
    for i in range(n):
        dt = _HOURLY_START + datetime.timedelta(hours=i)
        c = round(o + step, 6)
        h = round(c + hl_frac, 6)
        lo = round(o - hl_frac, 6)
        rows.append([
            start_id + i, ticker,
            dt.strftime('%Y-%m-%d'), dt.strftime('%H:%M:%S'),
            f'{o:.5f}', f'{h:.5f}', f'{lo:.5f}', f'{c:.5f}',
        ])
        o = c
    return rows


def _all_hourly():
    # (ticker, base_open, step_per_bar, high_low_half_range)
    # Steps chosen so final price matches prior sample data closely.
    specs = [
        ('GBPJPY', 185.000, 0.03284,  0.150),   # →191.54
        ('EURUSD',  1.0620, 0.000130, 0.00060),  # →1.0879
        ('GBPUSD',  1.2450, 0.000120, 0.00060),  # →1.2689
        ('USDJPY', 146.000, 0.02191,  0.100),    # →150.36
        ('USDCAD',  1.3320, 0.000170, 0.00075),  # →1.3659
        ('EURGBP',  0.8420, 0.000090, 0.00035),  # →0.8599
        ('EURJPY', 155.000, 0.04296,  0.150),    # →163.55
        ('EURCAD',  1.4120, 0.000250, 0.00075),  # →1.4618
    ]
    rows = []
    sid = 1
    for ticker, base_open, step, hl in specs:
        rows.extend(_gen_bars(ticker, base_open, step, hl, start_id=sid))
        sid += 200
    return rows


# ---------------------------------------------------------------------------
# Signal-generator helper — builds SigGenTP + MAP rows for every cross
# ---------------------------------------------------------------------------

_ENGINES_CROSSES = [
    ('GBPJPYeng01', 'GBPJPY'),
    ('EURUSDeng01', 'EURUSD'),
    ('GBPUSDeng01', 'GBPUSD'),
    ('USDJPYeng01', 'USDJPY'),
    ('USDCADeng01', 'USDCAD'),
    ('EURGBPeng01', 'EURGBP'),
    ('EURJPYeng01', 'EURJPY'),
    ('EURCADeng01', 'EURCAD'),
]

_MA_PAIRS = [
    ( 6,   7),   # tight — existing
    (12,  13),   # tight — existing
    ( 6,  13),   # short-term momentum
    ( 8,  21),   # Fibonacci intraday
    (20,  50),   # swing
    (50, 200),   # Golden/Death Cross
]


def _build_siggen_rows():
    """Return (siggentp_rows, map_rows) for all engines × all MA pairs."""
    sg_rows, map_rows = [], []
    sg_id, map_id = 1, 1
    for eng, cross in _ENGINES_CROSSES:
        for fast, slow in _MA_PAIRS:
            name = f'{cross}_TP_{fast}_{slow}'
            sg_rows.append([sg_id, name, fast, slow])
            map_rows.append([map_id, eng, name])
            sg_id  += 1
            map_id += 1
    return sg_rows, map_rows


_SIGGENTP_ROWS, _MAP_TE_SG_ROWS = _build_siggen_rows()

# ---------------------------------------------------------------------------
# Sample data
# ---------------------------------------------------------------------------

TABLES = {
    'FXCross': {
        'fields': ['Id', 'FXCross', 'BaseCcy', 'QuoteCcy', 'Scalar', 'IP'],
        'rows': [
            # G7 pairs vs USD
            [1, 'GBPJPY', 'GBP', 'JPY', '100.0000', '192.168.1.1'],
            [2, 'EURUSD', 'EUR', 'USD',   '1.0000', '192.168.1.2'],
            [3, 'GBPUSD', 'GBP', 'USD',   '1.0000', '192.168.1.3'],
            [4, 'USDJPY', 'USD', 'JPY', '100.0000', '192.168.1.4'],
            [5, 'USDCAD', 'USD', 'CAD',   '1.0000', '192.168.1.5'],
            # G7 pairs vs EUR
            [6, 'EURGBP', 'EUR', 'GBP',   '1.0000', '192.168.1.6'],
            [7, 'EURJPY', 'EUR', 'JPY', '100.0000', '192.168.1.7'],
            [8, 'EURCAD', 'EUR', 'CAD',   '1.0000', '192.168.1.8'],
            # Other
            [9, 'AUDUSD', 'AUD', 'USD',   '1.0000', '192.168.1.9'],
        ],
    },
    'HourlyData': {
        'fields': ['Id', 'ticker', 'Date', 'Time', 'Open', 'High', 'Low', 'Close'],
        # 200 bars per cross × 8 crosses = 1600 rows, generated by _all_hourly().
        # Covers SMA-200 and all smaller MA pairs from first bar.
        'rows': _all_hourly(),
    },
    'TEngine': {
        'fields': ['Id', 'TEngine', 'Instrument'],
        'rows': [
            # G7 vs USD
            [1, 'GBPJPYeng01', 'GBPJPY'],
            [2, 'EURUSDeng01', 'EURUSD'],
            [3, 'GBPUSDeng01', 'GBPUSD'],
            [4, 'USDJPYeng01', 'USDJPY'],
            [5, 'USDCADeng01', 'USDCAD'],
            # G7 vs EUR
            [6, 'EURGBPeng01', 'EURGBP'],
            [7, 'EURJPYeng01', 'EURJPY'],
            [8, 'EURCADeng01', 'EURCAD'],
        ],
    },
    'MAP_Pfo_TEngine': {
        'fields': ['Id', 'Portfolio', 'TEngine', 'Weight'],
        'rows': [
            [1, 'FX Portfolio 1', 'GBPJPYeng01', '0.1250'],
            [2, 'FX Portfolio 1', 'EURUSDeng01', '0.1250'],
            [3, 'FX Portfolio 1', 'GBPUSDeng01', '0.1250'],
            [4, 'FX Portfolio 1', 'USDJPYeng01', '0.1250'],
            [5, 'FX Portfolio 1', 'USDCADeng01', '0.1250'],
            [6, 'FX Portfolio 1', 'EURGBPeng01', '0.1250'],
            [7, 'FX Portfolio 1', 'EURJPYeng01', '0.1250'],
            [8, 'FX Portfolio 1', 'EURCADeng01', '0.1250'],
        ],
    },
    'MAP_TEngine_SigGen': {
        'fields': ['Id', 'TEngine', 'SigGen'],
        # Generated by _build_siggen_rows(): 8 engines × 6 MA pairs = 48 rows.
        'rows': _MAP_TE_SG_ROWS,
    },
    'SigGenTP': {
        'fields': ['Id', 'SigGen', 'nMA6', 'nMA6_1'],
        # Generated by _build_siggen_rows(): 8 crosses × 6 MA pairs = 48 rows.
        'rows': _SIGGENTP_ROWS,
    },
    'fx_table': {
        'fields': ['Id', 'Instrument', 'curncy1', 'curncy2'],
        'rows': [
            [1, 'GBPJPY Curncy', 'GBP', 'JPY'],
            [2, 'EURUSD Curncy', 'EUR', 'USD'],
            [3, 'USDJPY Curncy', 'USD', 'JPY'],
        ],
    },
    'fx_data': {
        'fields': ['Id', 'Instrument', 'TSDate', 'PX_OPEN', 'PX_HIGH', 'PX_LOW', 'PX_CLOSE'],
        'rows': [
            [1, 'GBPJPY Curncy', '20260304', '188.00000', '190.51000', '187.65000', '190.42000'],
            [2, 'GBPJPY Curncy', '20260303', '187.20000', '188.50000', '186.90000', '188.00000'],
            [3, 'GBPJPY Curncy', '20260228', '186.50000', '187.80000', '186.10000', '187.20000'],
            [4, 'GBPJPY Curncy', '20260227', '185.80000', '186.90000', '185.50000', '186.50000'],
            [5, 'GBPJPY Curncy', '20260226', '185.20000', '186.10000', '184.90000', '185.80000'],
        ],
    },
    'tf_engines': {
        'fields': ['Id', 'Engine', 'Slow', 'Fast', 'Buffer'],
        'rows': [
            [1, 'TF_GBPJPY_32_8',  32,  8, '0.0020'],
            [2, 'TF_GBPJPY_64_16', 64, 16, '0.0030'],
            [3, 'TF_EURUSD_32_8',  32,  8, '0.0010'],
        ],
    },
    # Empty tables — headers only; the app appends rows at runtime
    'futures_data': {
        'fields': ['Id', 'TSDate', 'Instrument_ID', 'NM', 'PX_Open', 'PX_HIGH', 'PX_LOW', 'PX_CLOSE'],
        'rows': [],
    },
    'state_tf_futures': {
        'fields': [
            'Id', 'Instrument', 'Engine', 'TSDate', 'NM', 'FM',
            'PX_OPEN', 'PX_HIGH', 'PX_LOW', 'PX_CLOSE', 'FM_CLOSE',
            'ATR', '20EMA(ATR)', 'EMAFast', 'EMASlow', 'Buffer', 'Sig',
        ],
        'rows': [],
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def write_table(data_dir, name, spec):
    path = os.path.join(data_dir, name + '.csv')
    with open(path, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(spec['fields'])
        w.writerows(spec['rows'])


def verify(data_dir):
    print(f"\n{'Table':<25} {'Rows':>6}")
    print('-' * 33)
    for name in TABLES:
        path = os.path.join(data_dir, name + '.csv')
        try:
            with open(path, newline='', encoding='utf-8') as f:
                count = sum(1 for _ in csv.DictReader(f))
        except FileNotFoundError:
            count = -1
        print(f"{name:<25} {count:>6}")
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    default_data_dir = os.path.join(here, 'data')

    parser = argparse.ArgumentParser(description='Set up FXTS CSV data files')
    parser.add_argument('--data-dir', default=default_data_dir,
                        help='Directory for CSV files (default: ./data)')
    parser.add_argument('--verify', action='store_true',
                        help='Show row counts only, do not recreate files')
    args = parser.parse_args()

    data_dir = args.data_dir
    os.makedirs(data_dir, exist_ok=True)

    if args.verify:
        print(f"Verifying data directory: {data_dir}")
        verify(data_dir)
    else:
        print(f"Writing CSV files to: {data_dir}")
        for name, spec in TABLES.items():
            write_table(data_dir, name, spec)
            print(f"  {name}.csv  ({len(spec['rows'])} rows)")
        verify(data_dir)

    print("Done.")


if __name__ == '__main__':
    main()
